import { describe, expect, test } from 'vitest';
import {
	createGroup,
	generateKeyPackage,
	getGroupMembers,
	unsafeTestingAuthenticationService
} from 'ts-mls';
import {
	addMembersToGroup,
	createCordnMetadataCapabilities,
	createCredential,
	encodeWelcomeBase64,
	getCordnCipherSuite,
	joinGroupFromWelcome,
	makeNobleEd25519Signature
} from './chatMlsUtils';

describe('addMembersToGroup()', () => {
	test('adds multiple members in one commit with a single welcome covering all joiners', async () => {
		const cipherSuite = await getCordnCipherSuite();
		const context = { cipherSuite, authService: unsafeTestingAuthenticationService };

		const creator = await generateKeyPackage({
			credential: createCredential('aa'.repeat(32)),
			capabilities: createCordnMetadataCapabilities(),
			cipherSuite
		});
		const state = await createGroup({
			context,
			groupId: new TextEncoder().encode('batch-add-test'),
			keyPackage: creator.publicPackage,
			privateKeyPackage: creator.privatePackage
		});

		const joiners = await Promise.all(
			['bb'.repeat(32), 'cc'.repeat(32)].map((stablePubkey) =>
				generateKeyPackage({
					credential: createCredential(stablePubkey),
					capabilities: createCordnMetadataCapabilities(),
					cipherSuite
				})
			)
		);

		const result = await addMembersToGroup({
			state,
			memberKeyPackages: joiners.map((joiner) => joiner.publicPackage)
		});

		expect(result.newState.groupContext.epoch).toBe(1n);
		expect(getGroupMembers(result.newState)).toHaveLength(3);
		expect(result.welcome.secrets).toHaveLength(2);

		const welcomeBase64 = encodeWelcomeBase64(result.welcome);
		const joinedStates = await Promise.all(
			joiners.map((joiner) =>
				joinGroupFromWelcome({
					welcomeBase64,
					keyPackage: joiner.publicPackage,
					privateKeyPackage: joiner.privatePackage
				})
			)
		);
		for (const joinedState of joinedStates) {
			expect(joinedState.groupContext.epoch).toBe(1n);
			expect(getGroupMembers(joinedState)).toHaveLength(3);
		}
	});
	describe('Ed25519 noble fallback', () => {
		test('roundtrips and stays interoperable with subtle-generated PKCS8 keys', async () => {
			const sig = makeNobleEd25519Signature();
			const message = new TextEncoder().encode('interop-test');

			const { signKey, publicKey } = await sig.keygen();
			const signature = await sig.sign(signKey, message);
			expect(await sig.verify(publicKey, message, signature)).toBe(true);
			expect(await sig.verify(publicKey, new TextEncoder().encode('other'), signature)).toBe(false);

			// Keys generated by WebCrypto (real devices) are PKCS8; the noble path must sign them.
			const kp = await crypto.subtle.generateKey('Ed25519', true, ['sign', 'verify']);
			const pkcs8 = new Uint8Array(await crypto.subtle.exportKey('pkcs8', kp.privateKey));
			expect(pkcs8.length).toBe(48);
			const viaNoble = await sig.sign(pkcs8, message);
			expect(
				await crypto.subtle.verify('Ed25519', kp.publicKey, new Uint8Array(viaNoble), message)
			).toBe(true);

			// And subtle-signed messages must verify via noble (raw 32-byte public key).
			const rawPub = new Uint8Array(await crypto.subtle.exportKey('raw', kp.publicKey));
			const viaSubtle = new Uint8Array(await crypto.subtle.sign('Ed25519', kp.privateKey, message));
			expect(await sig.verify(rawPub, message, viaSubtle)).toBe(true);
		});
	});
});
